#services:
#  dragonfly:
#    image: docker.dragonflydb.io/dragonflydb/dragonfly
#    container_name: dragonfly
#    hostname: dragonfly
#    privileged: true
#    ulimits:
#      memlock: -1
#    ports:
#      - "6379:6379"


version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
